python3: can't open file '/home/wellington/work/ud-tools/validate.py': [Errno 2] No such file or directory
